### ISSUE TITLE
Feature request: Switch between active debug configurations

### ISSUE THREAD

**Issue by thedriveman** [ArturoDent/launch-config#11]
Hi @ArturoDent, thank you for writing this awesome plugin!

Question: Would it possible to assign a shortcut to switch between 2 active debug sessions?

Context: 
Consider a multi-target (or "compound") configuration, where VS Code concurrently runs & debugs two processes (e.g., a React client and a node-based Server). 

Both processes send debug messages to the debug console panel, and one can select the active process either in the debug configuration dropdown menu (usually on the left pane, on the top) or in the debug console drop down menu.

The inconvenience is that as far as I can see, switching between the active sessions can only be done with the cursor.

**Comment by ArturoDent** [comment]
In v0.8.2 I have added two commands to switch to the next or previous active debug session.  Please see the `Commands` section of the README.  There are no default keybindings but the README shows how to make your own.

There is no straightforward way to switch between sessions (as the issues that follow discuss) so these commands do so through a few `list` navigation commands but it seems to work.  You can easily get the active debugSession but there is no api to **set** the active session unfortunately.  

https://github.com/microsoft/vscode/issues/39560  
https://github.com/microsoft/vscode/issues/108844

I will close this issue.  If you find any issues with these commands please file a new issue.
