### ISSUE TITLE
Use of launch in settings.json rather than launch.json

### ISSUE THREAD

**Issue by spoyser** [ArturoDent/launch-config#12]
First I would like to say this is a great extension to VS code and I have been happily using it for months now.
I recently discovered that rather than having to have the launch configurations defined in launch.json they can actually be defined  in settings.json, eg

```
"launch": {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Python: Debug Current File",
                "type": "python",
                "request": "launch",
                "program": "${file}",
                "cwd": "${fileDirname}",
                "console": "integratedTerminal",
            },
etc etc
```

This is great because they can be added to the user settings.json file and therefore all instance of VS code automatically get these launch configurations. This cannot be achieved using launch.json. (because you cannot have a user launch.json)

Unfortunately at the moment this extension only works with launch configurations defined in launch.json NOT settings.json.

Can this be fixed?

**Comment by ArturoDent** [comment]
I'll look into this.  It should be doable.

**Comment by spoyser** [comment]
> I'll look into this. It should be doable.

That would be great :)

**Comment by ArturoDent** [comment]
@spoyser Do you ever have both a User settings launch configs and a launch.json in the workspace?  Typically vscode returns launch.json launch configs since workspace configs have a higher priority than global User Setting configs.

And if you do have both - do you want to access **both** in this extension's  `launches` setting and/or `launches` keybinding?

**Comment by spoyser** [comment]
@ArturoDent to be honest I now just have user settings, rather than using the launch.json, as there doesn't seem to be any benefit to having both.
Also, by only having the launch configs in the settings.json when I click the cog to edit the launch configs VSCode automatically open the settings.json file at the correct point (which is convenient), if you have both then the cog opens the launch.json file instead (presumably as you say because it has a higher priority).
Saying all that though, I guess it would make sense to support both simultaneously, unless that is not possible, in which case having an extension setting to switch to use the settings.json would work for me. 
Thanks.

**Comment by ArturoDent** [comment]
I have pushed a pre-release version for testing which includes the ability to read `launch` configurations in the **user settings**.  To download it, go to the `Launch Configs` extension in your Extensions Side Bar entry and open it - it should give you the `pre-release` option there.  Or the gear icon in the `Launch Configs`  Side Bar entry.

Read the README for more info on the pre-release version.  There is a problem with compound configurations which may be insurmountable as vscode does not really support scoping launch configurations from the user settings.  See this issue: https://github.com/microsoft/vscode/issues/109083

**Comment by spoyser** [comment]
Switched to the pre-release version.
Looks like it is working :) (thanks for taking the time to implement it)
However, one observation, when I enter the settings for this extension in the json file they still auto fill with the workspace folder in brackets at the end, e.g.

"GDB Attach (T1234) [Settings]"

Where T1234 is the root folder of the workspace.
This doesn't seem right since the launch configurations shouldn't be associated with any particular workspace. And sort of defeats the purpose, since I would have to add a new launches settings every time the workspace folder changes.

**Comment by ArturoDent** [comment]
The workspace entry isn't actually used for anything when there is also a `[Settings]` entry but does allow me to use the same regex to parse all strings from the `launches` setting.  I may look into removing the workspace entry to reduce confusion on those.

For now, I will close this as implemented.  Please file a new issue if you find any problems with the new user setting functionality.  Thank you.

**Comment by spoyser** [comment]
Many thanks for your continued hard work in developing this extension it is most appreciated.

I can confirm that the workspace entry isn't used as I have now changed it in my config to "User", e.g. 

```
"launches": {

        "GDBAttach": "GDB Attach  (User) [Settings]",

        "Python": "Python: Debug Current File  (User) [Settings]",

    },
```

And that still works :)

**Comment by spoyser** [comment]
Hi again, I have just switched the the latest release version (0.8.3) and the new functionality has stopped working :(

Also, when the auto-fill feature is used it no longer adds the "[settings]" to the name of the configuration.

I can confirm that the original functionality DOES still work (i.e. having configs in the launch.json file).

**Comment by ArturoDent** [comment]
Yes, the settings functionality is only in the pre-release version.   It is there for testing before general release.  In the meantime v0.8.3 included 2 new commands for going to the next/previous debug session via a keybinding.

The pre-release functionality will be merged into stable soon.

**Comment by xboxfly15** [comment]
Hi, I'm wanting to do the same and cannot find where to select the pre-release version, this is preventing my use of the extension. I've looked in the marketplace and in the extensions side bar cog and all I can see is 0.8.3.
Please can this be pushed to master branch or the ability to select the pre-release version again.

**Comment by spoyser** [comment]
I stopped using this extension (over time I ended up far too may launch configurations > 15) and just created the following key-binding:

{
    "key" : "ctrl+d",
    "command" : "workbench.action.debug.selectandstart",
    "when" : "editorTextFocus",
}

Ctrl D, then just brings up a quick-pick menu with all my launch configs, very simple and less maintenance :)
