### ISSUE TITLE
typo in README

### ISSUE THREAD

**Issue by rioj7** [ArturoDent/launch-config#16]
In **Extension Settings** is the string:

> That folder name is used to resolve which `launch.js` to look in for the corresponding configuration

`launch.js` should be `launch.json`

----

In **Known Issues**

number 3 is "missing"

----

**Release Notes**

VSC Marketplace supports the `CHANGELOG.md` file

**Comment by ArturoDent** [comment]
Thanks, I made these changes.  Will be incorporated in a later version.
