### ISSUE TITLE
Global Settings for behaviour

### ISSUE THREAD

**Issue by SFagone** [ArturoDent/launch-config#18]
I have following tasks config
{
"version": "2.0.0",
  "tasks": [
    {
      "label": "builddotnet",
      "detail": "Builds the application",
      "command": "dotnet build \"${input:remember.SLNorProjPath}\"",
      "type": "shell",
      "problemMatcher": "$msCompile"
    },
    {
      "label": "builddotnetwithargs",
      "detail": "Builds the application",
      "command": "dotnet build \"${input:remember.SLNorProjPath}\" ${input:remember.BuildArgs}",
      "type": "shell",
      "problemMatcher": "$msCompile"
    }
  ],
  //VSCode Extension https://marketplace.visualstudio.com/items?itemName=ArturoDent.launch-config
  "inputs": [
    {
      "id": "remember.SLNorProjPath",
      "type": "command",
      "command": "extension.commandvariable.remember",
      "args": { "key": "SLNorProjPath" }
    },
    {
      "id": "remember.BuildArgs",
      "type": "command",
      "command": "extension.commandvariable.remember",
      "args": { "key": "BuildArgs" }
    }
  ]
}

I need now two tasks "builddotnet" and "builddotnetwithargs".

I set the variable as following
"inputs": [
        {
          "id": "rememberConfig.Service.SLNorProjPath",
          "type": "command",
          "command": "extension.commandvariable.remember",
          "args": {
            "store": {"SLNorProjPath":"${workspaceFolder}/src/SGOIMDispatcher.Service/SGOIMDispatcher.Service.csproj"}
          }
        },
        {
            "id": "rememberConfig.Service.ReleaseBuildArgs",
            "type": "command",
            "command": "extension.commandvariable.remember",
            "args": {
              "store": {"BuildArgs":"-c Release"}
            }
          }
      ]

I trigger the remember config by calling one of it or multiple of it in the launch config they need to be, eg:

            "name": "SGOIMDispatcher.Service_Release",
            //make static analyzer happy. debugs symbols are not emitted, so type and request not needed...
            "type": "clr",
             "request": "launch",
            //build in release without debug symbols
            "preLaunchTask": "builddotnetwithargs",
            "program": "${workspaceFolder}/bin/Release/net48/SGOIMDispatcher.exe",
            //Used to trigger keyvalue store, returns empty as args
            "args": ["${input:rememberConfig.Service.SLNorProjPath}",
                    "${input:rememberConfig.Service.ReleaseBuildArgs}"
            ],
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "internalConsoleOptions": "openOnSessionStart"
        }

If now i don't set a value that is used in a task i get the error "i cannot remember". If it wouldn't throw this error I could use just one task with both input variables defined in it. So it would be nice to have an enhancement where i can controll the behaviour if a value is not throw (e.g. return empty or throw).

Also a option/mechanism that can contcat multiple stored keys with the same keyname when defined instead of overriding the value in the key/valuestore could be usefull. 

e.g.
"store": {"BuildArgs":"-path [path]"}
"store": {"BuildArgs":"-c release"}

${input:remember.BuildArgs) -> "-path [path]> -c release".

With this i can reuse the defined args for the different launch.configs without rewriting them

**Comment by rioj7** [comment]
@SFagone  You can use persistent storage of the remember store between VSC instantiations.

You could write a task that initializes the remember entries to an empty string

I can add the feature that by decorating the remember key you can extend the string.

`"store": {"BuildArgs+=": "-c release"}` : just concat the new string, if not in store just assign

`"store": {"BuildArgs+= ": "-c release"}` : if not in store just assign the new string, if already in store concat the character after the `=` before concat the string, here concat with spaces

`"store": {"BuildArgs+=,": "-c release"}` : use `,` to concatenate the parts

**Comment by SFagone** [comment]
Thank you for de idea with the default initialation via. task that helps for sure!

As for the concat part, maybe something like this with an array is a more expressive option:
`"store": {"BuildArgs":[{"value":""}, {"type":"concat"}, {"Delimiter":"<specify delimiter>"}, {"wrapvaluewith": "<chracter or string that is inserted at beginning and end"}]`

Like this it would be clear, more flexible and easily extendable. As far as i know its possible to pass an array to the function. you need to check for array and convert it to string accordingly otherwhise it will be stored as array in the key/value store and throw an error when reading with "input:rememberid"

What do you think?

**Comment by rioj7** [comment]
@SFagone Why don't you create an issue at the repo https://github.com/rioj7/command-variable
  
  Maybe you can transfer (menu in the right side bar at the top) this issue or Arturo will do it.
  
----

  If I go your way it would be
  
  ```json
  "store": {
      "BuildArgs": {"value":"-c release", "type":"concat", "delimiter":" "}
  }
  ```
  
  If you want a wrap you can add it to the `value`

**Comment by ArturoDent** [comment]
Is there anything for me to do on this issue in this extension's codebase?

**Comment by rioj7** [comment]
@ArturoDent The OP has created the issue in the wrong repo.

I asked OP to re-create or transfer but no responds yet.

I can't transfer it to the https://github.com/rioj7/command-variable repo

Can you do this?

**Comment by ArturoDent** [comment]
@rioj7 I can't either, see https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

You have to an owner of both repositories.

So closing this as filed in wrong repository.
