### ISSUE TITLE
Provided setting does not match actual setting

### ISSUE THREAD

**Issue by DJ4ddi** [ArturoDent/launch-config#2]
The documentation (as well as autocomplete and the extension capabilities) specifies `launches.ifDebugSessionRunning`, but the setting that is actually used is `launch.ifDebugSessionRunning`.

**Comment by ArturoDent** [comment]
You may have to reload vscode or hopefully not uninstall/reinstall the extension since you had the previous version with the prior spelling.  With v0.6.7, `launch.ifDebugSessionRunning` is dimmed with the error message `Unknown Configuration Setting` as it should be.

**Comment by DJ4ddi** [comment]
Yes, it is, but the code is still looking for the wrong setting:
https://github.com/ArturoDent/launch-config/blob/4a058c64f2ed21b926e6efa14a49a7acbae44be8/src/handleDebugSession.js#L93

**Comment by ArturoDent** [comment]
Damn, need to do more global searches.  Thanks, fixed.
