### ISSUE TITLE
[Feature] Invoke without keybinding

### ISSUE THREAD

**Issue by RandScullard** [ArturoDent/launch-config#9]
Currently it seems like the only way to invoke my launch config is with a keybinding. This is a bit awkward since keybindings are global but my launch config is specific to a particular project. It would be nice if I could also invoke my launch config via the F1 command palette.

**Comment by ArturoDent** [comment]
Hi, 

This can probably be done but is a little awkward as vscode would require a reload after any new launch config or `launches` setting change is created - the Command Palette is only populated on a load/reload.

Do you want your `launches` settings names that you create to be available in the Command Palette or use the names directly from your `launch.json`?

**Comment by RandScullard** [comment]
Couldn't the command in the Command Palette prompt for which launch config to invoke? Like the **Debug: Select and Start Debugging** command?

**Comment by ArturoDent** [comment]
So you are looking for a Quick Pick to open with the names you gave various launch configurations in the `launches` setting:

```jsonc
{
  "launches": { 
    "test-debug": "Launch File (Test Bed)", 
    "Start2Debuggers": "Start 2 node debuggers (Test Bed)",
    "Start2DebuggersArray": ["First Debugger (Test Bed)", "Second Debugger (Test Bed)"],
    "LaunchChrome": "Launch Chrome against localhost (Test Bed)",
    "LaunchFirstDebugger": "First Debugger (Test Bed)"
  }
}
```

So those five keys, like `Start2DebuggersArray` would appear in the Quick Pick and selecting it would start that debug configuration?

Should that Quick Pick have only those entries (from the `launches` setting) or also all the other launch configurations in your `launch.json`, user and workspace settings?

**Comment by RandScullard** [comment]
Yes, that is what I had in mind. I guess it would be best if it included all the other launch configurations as well, because I could see using it as a replacement for **Debug: Select and Start Debugging**.

However, since I wrote up this issue I have stopped using launch-config because it turned out to be problematic in my scenario. I have two executables that I want to build and launch, and they share a common library. Each executable's build also builds the common library. I found that when I used launch-config to build and debug them both at once, the builds would intermittently fail on the common library because of file contention. It happened often enough that I stopped using launch-config and now I just launch each one manually. I still think "invoke without keybinding" would be a good enhancement to launch-config, but I personally won't be able to take advantage of it - I thought you should know.

**Comment by ArturoDent** [comment]
If possible, you should put your builds into a `preLaunchTask` (which itself could depend on two other tasks).  The `preLaunchTask` could be an arg to a launch or compound launch configuration.  I assume that vscode would then handle those in a sequential fashion.  

I'll close as this hasn't been requested by anyone else.  Thanks.
